M48
; DRILL file {KiCad 7.0.7} date Thu Nov  2 14:39:52 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-02T14:39:52+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X0.13Y-1.67
X0.13Y-1.94
X3.17Y-0.14
X3.17Y-3.47
T0
M30
